name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Test
        run: xcodebuild -project ZBSimplePluginManager.xcodeproj -scheme ZBSimplePluginManagerTests test -destination 'platform=iOS Simulator,name=iPhone 16'
